require 'rack/test'
require 'json'
require_relative '../../app/api'

# Write the code you wish you had
#  - then fill in the implementation
#  - design thing's from the caller's perspective

module ExpenseTracker

	RSpec.describe 'Expense Tracker API' do
		include Rack::Test::Methods

		# fixes: undefined local variable or method ‘app’ error message
		# test method requires an 'app' method that returns the web app
		def app
			ExpenseTracker::API.new
		end

		it "records submitted expenses" do
			# we can use either strings or symbols for the keys - JSON treats them th same
			coffee ={
					'payee' => 'Starbucks',
					'amount' => 5.75,
					'date' => '2017-06-10'
			}

			# 'posting' key/value pairs to the '/expenses' endpoint
			# post/get requests can be generated by a gui/cli app or rspec
			# 'post' is a Rack:Test method which simulates http post
			post '/expenses', JSON.generate(coffee)
		end

	end

end